services:
  - type: web
    name: gsb-pharmacy-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://gsb-pharmacy-backend.onrender.com 